version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.27
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=my-db
      - MYSQL_ROOT_PASSWORD=password
