version: '3.9'
services:
  postgres:
    image: postgres:17.1
    container_name: psql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce_db
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - ecommerce-network

volumes:
  postgres:

networks:
  ecommerce-network:
